services:
  - type: worker
    name: otp-telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt && playwright install chromium && playwright install-deps chromium
    startCommand: python run_bot.py
    plan: free
    region: oregon
    branch: main